### PR TITLE
Updated Greg's critique section with actual critique

### PR DESCRIPTION
**Pull request by taoeffect**
Hi Paul,

Your section on me is full of false statements that do not represent [my actual critique](https://twitter.com/taoeffect/status/876227634593583104).

Kindly either remove [the nonsense](https://twitter.com/taoeffect/status/876212719506006016) you have, or post something actually representative.

Thanks!
Greg

### CODE REVIEW

**Comment by CryptAxe** [comment]
You were quoted and links to the twitter conversation are included in the 2 paragraphs about your statements. I just read through the conversation again and do not see any way that your argument is being misrepresented. If your new critique demonstrates anything, it's that you still haven't read what has been suggested to you. As others pointed out, you can't expect to critique something that you don't know about and receive thanks.  

If you think that the PRC have control of bitcoin mining, and are willing to damage their investment out of spite (without a profit motive), why don't they just attack bitcoin right now? It seems like you think a 51% attack isn't a big deal unless drivechains are active in which case it would become an issue. People already want a PoW change so wouldn't giving everyone a great reason (including those who currently are against it) be a really bad idea? Part of the design of drivechains makes it so that this behavior (attacking a sidechain) would not only be incredibly obvious to everyone on the network, but would take so long (months) that responding appropriately is possible. Drivechains, like bitcoin mining, provide more income to a miner verifying sidechains than they would get by trying to mess with the system. Miners like having more money, they don't like losing money or missing out on any potential profits.

http://www.truthcoin.info/blog/drivechain/#drivechains-security specifically read from "Level 3" which is an example of drivechains operating in an environment with a 51% miner cartel.  

If your new critiques still stand they should be added to the peer review page. If there's a specific part of the existing page that isn't true, we should fix it. I don't see anything that isn't true, please point out what part of the following is false:

> Later that very day, Greg took to Twitter to express his opinion –which, in addition to $3.75 will get you an iced mocha frappuccino at Starbucks– that the Drivechain security model is “a complete regression back to banking”. He also implied that DC would “[turn] miners into the exchange everyone goes through” and that DC “defeats the purpose of Bitcoin.”
> 
> However, during the ensuring conversation, he admitted to have not done any background reading whatsoever. Mashuri Clark then asked “If you’re not going to read up on it then why should anyone listen to your critiques?” to which Greg replied “I agree, they shouldn’t”.

**Comment by taoeffect** [comment]
>  please point out what part of the following is false:

I did, on twitter:

- https://twitter.com/taoeffect/status/876214401266630656
- https://twitter.com/taoeffect/status/876212466052513792
- https://twitter.com/taoeffect/status/876212325660807169

That narrative is bs. It says I had "not done any background reading whatsoever" when I did. He reversed the timeline of events to make it sound like my later critiques were based on zero reading. That is false.

> why don't they just attack bitcoin right now?

> It seems like you think a 51% attack isn't a big deal unless drivechains are active in which case it would become an issue.

This is a straw man / total misrepresentation of my argument. Did you miss [this part](https://twitter.com/taoeffect/status/875951606486810625) of my argument as well?

> Part of the design of drivechains makes it so that this behavior (attacking a sidechain) would not only be incredibly obvious to everyone on the network, but would take so long (months) that responding appropriately is possible.

As far as I can tell, it would be pretty much like today with a bank that seized your assets. Not much you can do.

Anyway, please fix the false statements and mischaracterizations on your website.

**Comment by CryptAxe** [comment]
Well if you don't dispute that the quotes on the website are from your twitter, and you weren't hacked or anything I'm not sure how it's possible to consider this false information. The words came from you.

> This is a straw man / total misrepresentation of my argument

It's not fallacious to consider all aspects of an argument. You don't get to pick which parts of your position I'm allowed to question.

> As far as I can tell, it would be pretty much like today with a bank that seized your assets. Not much you can do.

So if bitcoin stopped working for any reason it would be a bank at that point?

**Comment by taoeffect** [comment]
> Well if you don't dispute that the quotes on the website are from your twitter, and you weren't hacked or anything I'm not sure how it's possible to consider this false information. The words came from you.

Wow.

I think I actually prefer at this point for the website to stay as is, so that everyone who is reading it and also comes across this pull request sees how either dumb or dishonest you are.

The concept of taking quotes out of context and using that false context to create a totally false narrative escapes you.

**Comment by taoeffect** [comment]
> It's not fallacious to consider all aspects of an argument. You don't get to pick which parts of your position I'm allowed to question.

Again:

> This is a straw man / total misrepresentation of my argument. Did you miss [this part](https://twitter.com/taoeffect/status/875951606486810625) of my argument as well?

**Comment by CryptAxe** [comment]
> I think I actually prefer at this point for the website to stay as is, so that everyone who is reading it and also comes across this pull request sees how either dumb or dishonest you are.

Sounds good to me.

**Pull request closed without merging**
